matuck_library_chillingdmca:
    pattern: /admin/chillingdmca
    defaults: { _controller: matuckLibraryBundle:Chillingdmca:index }
matuck_library_chillingdmca_new:
    pattern: /chillingdmca/new/book_id/{id}
    defaults: { _controller: matuckLibraryBundle:Chillingdmca:new }
matuck_library_chillingdmca_create:
    pattern: /chillingdmca/create
    defaults: { _controller: matuckLibraryBundle:Chillingdmca:create }
matuck_library_chillingdmca_edit:
    pattern: /admin/chillingdmca/edit/{id}
    defaults: { _controller: matuckLibraryBundle:Chillingdmca:edit }
matuck_library_chillingdmca_update:
    pattern: /admin/chillingdmca/update/{id}
    defaults: { _controller: matuckLibraryBundle:Chillingdmca:update }